version: '3.7'

services:
  northwind.backoffice.web:
    image: ${DOCKER_REGISTRY-}northwindbackoffice
    build:
      context: .
      dockerfile: Northwind.Backoffice.Web/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      SA_PASSWORD: "P@ssw0rd!"
      ACCEPT_EULA: "Y"
