# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action@v3.2
      with:
        # Paste output of `az ad sp create-for-rbac -o json` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Provide the name of a resource group.
        resourceGroupName: "northwind-test-rg"
        # Specify the path to the Azure Resource Manager template.
        templateLocation: src/infrastructure/azuredeploy.json
        # Specifies the name of the resource group deployment to create.
        deploymentName: "Initial"
        # Specify either path to the Azure Resource Manager parameters file or pass them as 'key1=value1;key2=value2;...'.
        parameters: src/infrastructure/azuredeploy.parameters.json
